version: '3.8'

services:
  app:
    build: ./api  # Указываем путь к директории с Dockerfile
    environment:
      - PYTHONPATH=./  # Указываем путь к директории с модулями приложения
      - FLASK_ENV=development  # Устанавливаем режим разработки
      - DATABASE_URL=postgresql://auction:auction@localhost:5432/auction  # URL для подключения к базе данных
    ports:
      - "8000:8000"  # Пробрасываем порт
    depends_on:
      - postgres  # Указываем зависимость от сервиса postgres
    networks:
      - es-net
    command: >
      sh -c "sleep 10 && flask run --host=0.0.0.0 --port=8000"  # Задержка перед запуском Flask

  postgres:
    image: postgres:latest
    ports:
      - "1000:5432"
    environment:
      POSTGRES_USER: auction
      POSTGRES_DB: auction
      POSTGRES_PASSWORD: auction
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - es-net

volumes:
  pg-data:
    driver: local

networks:
  es-net:
    driver: bridge